#!/usr/bin/bash
for repo in `find . -maxdepth 4 -name .git`; do
   base=`dirname $repo`
   pushd $base >/dev/null 2>&1
   echo '<====== Try pulling in ' $base
   git pull
   popd >/dev/null 2>&1
done
